# syntax=docker/dockerfile:1.7-labs

FROM oven/bun:1.3-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production

COPY --parents package.json bun.lock tsconfig.base.json apps/*/package.json packages/*/package.json ./
RUN bun install --frozen-lockfile

COPY packages/common ./packages/common
COPY packages/lexicon ./packages/lexicon
COPY apps/web ./apps/web

ARG VITE_RATAT_APPVIEW_URL
ENV VITE_RATAT_APPVIEW_URL=$VITE_RATAT_APPVIEW_URL

RUN bun run --cwd apps/web build

EXPOSE 3000
CMD ["bun", "run", "--cwd", "apps/web", "start"]
