/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth/client-metadata[.]json'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'
import { Route as ArtHandleRkeyRouteImport } from './routes/art.$handle.$rkey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth/client-metadata.json',
    path: '/oauth/client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtHandleRkeyRoute = ArtHandleRkeyRouteImport.update({
  id: '/art/$handle/$rkey',
  path: '/art/$handle/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/art/$handle/$rkey': typeof ArtHandleRkeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/art/$handle/$rkey': typeof ArtHandleRkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/art/$handle/$rkey': typeof ArtHandleRkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/profile/$handle'
    | '/art/$handle/$rkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/profile/$handle'
    | '/art/$handle/$rkey'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/profile/$handle'
    | '/art/$handle/$rkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
  ArtHandleRkeyRoute: typeof ArtHandleRkeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/client-metadata.json': {
      id: '/oauth/client-metadata.json'
      path: '/oauth/client-metadata.json'
      fullPath: '/oauth/client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/$handle/$rkey': {
      id: '/art/$handle/$rkey'
      path: '/art/$handle/$rkey'
      fullPath: '/art/$handle/$rkey'
      preLoaderRoute: typeof ArtHandleRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
  ProfileHandleRoute: ProfileHandleRoute,
  ArtHandleRkeyRoute: ArtHandleRkeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
